[general]
import = [
  "~/.config/alacritty/themes/one_light.toml"
]
live_config_reload = true

[window]
padding.x = 10
padding.y = 0
dynamic_padding = true

[font]
normal.family = "Hack Nerd Font Mono"
normal.style = "Regular"
size = 15

[keyboard]
bindings = [
{ key = "V", mods = "Control|Shift", action = "ToggleViMode"},
{ key = "PageUp", mods = "Shift", action = "ScrollLineUp" },
{ key = "PageDown", mods = "Shift", action = "ScrollLineDown" },
{ key = "Tab", mods = "Control",       chars = "\u001b[1;5I" }, # Ctrl+Tab
{ key = "Tab", mods = "Control|Shift", chars = "\u001b[1;6I" }, # Ctrl+Shift+Tab
{ key = "Left", mods = "Alt", chars = "\u001bb" },
{ key = "Right", mods = "Alt", chars = "\u001bf" },
{ key = "Return", mods = "Shift", chars = "\u001B\r" }
]

[mouse]
hide_when_typing = true

