import = [
  "~/.config/alacritty/themes/github_dark.toml"
]

[ env ]
# TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "CodeNewRoman Nerd Font"
# offset.y = 2

#regular
size = 16

#for video
# size = 35.0

[keyboard]
bindings = [
{ key = "V", mods = "Control|Shift", action = "ToggleViMode"},
{ key = "PageUp", mods = "Shift", action = "ScrollLineUp" },
{ key = "PageDown", mods = "Shift", action = "ScrollLineDown" },
{ key = "Tab", mods = "Control",       chars = "\u001b[1;5I" }, # Ctrl+Tab
{ key = "Tab", mods = "Control|Shift", chars = "\u001b[1;6I" }, # Ctrl+Shift+Tab
]

